services:
  neo4j-sites:
    build: 
      context: ./neo4j-sites
      dockerfile: Dockerfile
    container_name: neo4j-sites
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASS: "test"
    command: ["python", "src/import.py"]

volumes:
  neo4j_data: